# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/opsforgeio/shipyard
    steps:
      - checkout
      - run:
          name: Run GO test suite
          command: |
            go get -v -t -d ./...
            go get -d github.com/stretchr/testify/assert
            go get github.com/tools/godep
            bash test.sh
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Install docker client
      #     command: |
      #       set -x
      #       VER="17.09.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv -f /tmp/docker/* /usr/bin
      # build and push Docker image
      - run:
          name: Build and push docker images
          command: |
            MAINT=opsforge
            IMAGE=shipyard
            TAG=latest
            docker build -t $MAINT/$IMAGE:$TAG -f Dockerfile.build
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $MAINT/$IMAGE:$TAG
