defaults: &defaults
  working_directory: /go/src/github.com/opsforgeio/shipyard
  docker:
    - image: circleci/golang:1.8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run GO test suite
          command: |
            go get -v -t -d ./...
            go get -d github.com/stretchr/testify/assert
            go get github.com/tools/godep
            bash test.sh

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build controller binary
          command: |
            make build
            cp controller/controller /tmp
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - controller

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Build and push docker images
          command: |
            cp /tmp/build/controller ./controller/
            chmod +x ./controller/controller
            make clean
            make image
            make release

workflows:
  version: 2
  cicd:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
