# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/opsforgeio/shipyard
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -d github.com/stretchr/testify/assert
      - run: go get github.com/tools/godep
      - run: bash test.sh
